#!/bin/bash

declare -a keys=(
admin_password
admin_token
backup_password
blazar_dbpass
blazar_pass
ceilometer_dbpass
ceilometer_pass
cinder_dbpass
cinder_pass
db_hammers_pass
db_readonly_pass
glance_dbpass
glance_pass
gnocchi_dbpass
gnocchi_pass
heat_dbpass
heat_domain_admin_password
heat_pass
horizon_secret_key
instance_metrics_writer_password
ironic_dbpass
ironic_pass
keystone_dbpass
metadata_proxy_shared_secret
mysql_root
neutron_dbpass
neutron_pass
nova_dbpass
nova_pass
nova_placement_dbpass
nova_placement_pass
rabbit_password
swift_pass
)

for i in ${keys[@]}; do
  x=`openssl rand -hex 12`
  echo "${i}: '$x'"
  crudini --set manifests/settings.pp '' \$${i} \'$x\'
done
