---
- hosts: puppetmaster
  pre_tasks:
    - import_tasks: tasks/base_packages.yml
  roles:
    - puppetmaster

- hosts: controller
  tasks:
    - import_tasks: tasks/base_packages.yml

    - name: Install CentOS OpenStack repository.
      package:
        name: "centos-release-openstack-{{ ciab_openstack_release }}.noarch"
      when: ansible_distribution == 'CentOS'

    - name: Install Puppet agent.
      package:
        name: puppet

    - name: Run Puppet.
      puppet:
        environment: ciab

    - name: Create virtualenv.
      block:
        - name: Create virtualenv directory.
          file:
            path: "{{ ansible_virtualenv }}"
            state: directory
        - name: Install virtualenv.
          package:
            name: python-virtualenv
            state: present
        - name: Install latest pip.
          pip:
            name: pip
            state: latest
            virtualenv: "{{ ansible_virtualenv }}"
        - name: Set fact for virtualenv path.
          set_fact:
            ansible_python_interpreter: "{{ ansible_virtualenv }}/bin/python"
          tags:
            - always

    - name: Install pip dependencies.
      pip:
        name: openstacksdk
        virtualenv: "{{ ansible_virtualenv }}"
