#!/usr/bin/env bash
set -e -u

taskset="${1:-all}"
globals="globals.yml"
inventory="hosts"

preinstall() {
  ansible-playbook step-1-preinstall.yml
}

install() {
  ansible-playbook step-2-install.yml \
    --extra-vars "@$globals" \
    --inventory "$inventory"
}

postinstall() {
  ansible-playbook step-3-postinstall.yml \
    --extra-vars "@$globals" \
    --inventory "$inventory"
}

case "$taskset" in
  all)
    test -f "$globals" || {
      echo "No global settings found in ./$globals - creating a new globals file..."
      preinstall
      exit 0
    }
    install && postinstall
    ;;
  preinstall)
    preinstall
    ;;
  install)
    install
    ;;
  postinstall)
    postinstall
    ;;
  *)
    echo "Unknown taskset '$taskset'. Valid options are:"
    echo "  - preinstall"
    echo "  - install"
    echo "  - postinstall"
    exit 1
    ;;
esac
