mod 'puppetlabs-apache', '2.3.1'
#mod 'puppetlabs-stdlib', '4.25.1'
mod 'puppetlabs-stdlib'
mod 'puppetlabs-ntp'
mod 'puppetlabs-apt'
mod 'puppet-staging'
mod 'puppet-boolean'
mod 'puppet-archive'
#mod 'camptocamp-kmod', '2.2.0'
mod 'camptocamp-kmod'
#mod 'duritong-sysctl', '0.0.12'
mod 'duritong-sysctl'
#mod 'saz-memcached', '2.6.0'
mod 'saz-memcached'
mod 'puppetlabs-mysql', '5.4.0'
mod 'puppetlabs-postgresql'
mod 'zleslie-permute'
#mod 'puppet-rabbitmq', '8.2.2'
mod 'puppet-rabbitmq'
#mod 'arioch-redis', '3.3.0'
mod 'arioch-redis'
#mod 'puppetlabs-docker', '2.0.0'
mod 'puppetlabs-docker'
#mod 'puppetlabs-concat', '4.2.1'
mod 'puppetlabs-concat'
#mod 'spjmurray-ceph', '4.0.0'
mod 'spjmurray-ceph'
#mod 'puppetlabs-inifile', '2.3.0'
mod 'puppetlabs-inifile'
#mod 'saz-timezone', '5.0.2'
mod 'saz-timezone'
#mod 'puppetlabs-haproxy', '0.4.1'
mod 'puppetlabs-haproxy'
#example42-network (v3.3.7)
mod 'example42-network'
mod 'lwf-remote_file', '1.1.3'
#pcfens-ca_cert (v1.6.1)
mod 'pcfens-ca_cert'
mod 'puppetlabs-xinetd'
mod 'puppetlabs-vcsrepo'
mod 'puppet-python'
mod 'stahnma-epel'

mod 'openstack-gnocchi',
    :git => 'https://github.com/openstack/puppet-gnocchi.git',
    :branch => 'stable/ocata'

mod 'openstack-openstacklib',
    :git => 'https://github.com/openstack/puppet-openstacklib.git',
    :branch => 'stable/ocata'

mod 'openstack-openstack_extras',
    :git => 'https://github.com/openstack/puppet-openstack_extras.git',
    :branch => 'stable/ocata'

mod 'openstack-keystone',
    :git => 'https://github.com/openstack/puppet-keystone.git',
    :branch => 'stable/ocata'

mod 'openstack-nova',
    :git => 'https://github.com/openstack/puppet-nova.git',
    :branch => 'stable/ocata'

mod 'openstack-glance',
    :git => 'https://github.com/openstack/puppet-glance.git',
    :branch => 'stable/ocata'

mod 'openstack-cinder',
    :git => 'https://github.com/openstack/puppet-cinder.git',
    :branch => 'stable/ocata'

mod 'openstack-vswitch',
    :git => 'https://github.com/openstack/puppet-vswitch.git',
    :branch => 'stable/ocata'

mod 'openstack-horizon',
    :git => 'https://github.com/openstack/puppet-horizon.git',
    :branch => 'stable/ocata'

mod 'openstack-neutron',
    :git => 'https://github.com/openstack/puppet-neutron.git',
    :branch => 'stable/ocata'

mod 'openstack-heat',
    :git => 'https://github.com/openstack/puppet-heat.git',
    :branch => 'stable/ocata'

mod 'openstack-ironic',
    :git => 'https://github.com/openstack/puppet-ironic.git',
    :branch => 'stable/ocata'

mod 'oslo',
    :git => 'https://github.com/openstack/puppet-oslo.git',
    :branch => 'stable/ocata'

mod 'blazar',
    :git => 'https://github.com/ChameleonCloud/puppet-blazar.git'

# This is a private GitHub repository - you must request access
mod 'chameleoncloud',
    :git => 'git@github.com:ChameleonCloud/puppet-chameleoncloud.git',
    :branch => 'ciab'
