---
- name: Install Puppet agent.
  package:
    name: puppet

- name: Run Puppet.
  puppet:
    environment: chi-in-a-box

- import_tasks: ironic.yml
  tags:
    - postinstall
    - ironic

- import_tasks: neutron.yml
  tags:
    - postinstall
    - neutron

- import_tasks: nova.yml
  tags:
    - postinstall
    - nova
