---
- name: Install Puppet agent.
  package:
    name: puppet

- name: Run Puppet.
  puppet:
    environment: ciab

- import_tasks: glance.yml
  tags:
    - postinstall
    - glance

- import_tasks: ironic.yml
  tags:
    - postinstall
    - ironic

- import_tasks: nova.yml
  tags:
    - postinstall
    - nova
