---
- name: Install Puppet agent.
  package:
    name: puppet

- name: Run Puppet.
  puppet:
    environment: ciab

- name: Create virtualenv.
  block:
    - name: Create virtualenv directory.
      file:
        path: "{{ controller_virtualenv }}"
        state: directory
    - name: Install virtualenv.
      package:
        name: python-virtualenv
        state: present
    - name: Install latest pip.
      pip:
        name: pip
        state: latest
        virtualenv: "{{ controller_virtualenv }}"
        virtualenv_site_packages: yes
    - name: Set fact for virtualenv path.
      set_fact:
        ansible_python_interpreter: "{{ controller_virtualenv }}/bin/python"
      tags:
        - always

- name: Install pip dependencies.
  pip:
    name: openstacksdk
    virtualenv: "{{ controller_virtualenv }}"

- import_tasks: glance.yml
  tags:
    - postinstall
    - glance

- import_tasks: ironic.yml
  tags:
    - postinstall
    - ironic

- import_tasks: nova.yml
  tags:
    - postinstall
    - nova
